<a href="https://colab.research.google.com/github/atasam2023/Cuaderno-de-Algebra-Lineal/blob/main/Copia_de_Untitled2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

$$ -Matrices-$$

.

$\underline{\text{"Nula"}}$

.


$\bullet{\text{"Matrices que los elementos que son 0"}}$

.

$\blacktriangle{\text{"EJEMPLO:"}}$

.

$$\begin{bmatrix}
0 & 0\\
0 & 0
\end{bmatrix}$$

.

------------------------------------------------------------------------------

.

###Matriz fila

.

Una matriz fila es aquella que tiene una sola fila y varios elementos en esa fila. Se denota de la siguiente manera:

.

\$[A = [a_1, a_2, a_3, \ldots, a_n]\$]

.

donde $a_1, a_2, a_3, \ldots, a_n$ son los elementos de la matriz.

.

###Matriz columna

.

Una matriz columna es aquella que tiene una sola columna y varios elementos en esa columna. Se denota de la siguiente manera:

.

$[
B = \begin{bmatrix}
b_1 \\
b_2 \\
b_3 \\
\vdots \\
b_m
\end{bmatrix}
]$

.


donde $b_1, b_2, b_3, \ldots, b_m$ son los elementos de la matriz.

.

###Matriz cuadrada

.

Una matriz cuadrada es aquella que tiene el mismo número de filas que de columnas. Se denota de la siguiente manera:

.

$[
C = \begin{bmatrix}
c_{11} & c_{12} & c_{13} \\
c_{21} & c_{22} & c_{23} \\
c_{31} & c_{32} & c_{33} \\
\end{bmatrix}
]$

.

donde $c_{ij}$ representa los elementos de la matriz.

.

------------------------------------------------------------------------------

.

$\underline{\text{"Matriz Diagonal"}}$

.

$\checkmark{a_{ij}$ = 0 , $\forall_{i} \neq j$}$

.

$\blacktriangle{\text{"EJEMPLO:"}}$

.

\begin{bmatrix}
1 & 0 & 0\\
0 & 2 & 0\\
0 & 0 & 3
\end{bmatrix}

.

------------------------------------------------------------------------------

.

$\underline{\text{"Matriz Triánuglo Superior"}}$

.

$\checkmark{Si a_{ij} = 0, \forall_{i} > j}$

.

$\blacktriangle{\text{"EJEMPLO:"}}$

.

\begin{bmatrix}
1 & 3 & 2\\
0 & 4 & 8\\
0 & 0 & 7\\
\end{bmatrix}

.

------------------------------------------------------------------------------

.

$\underline{\text{"Matriz Triánuglo Inferior"}}$

.

$\checkmark{Si $a_{ij} = 0, \forall_{i} < j}$

.

$\blacktriangle{\text{"EJEMPLO:"}}$

.

\begin{bmatrix}
2 & 0 & 0\\
0 & 9 & 0\\
9 & 8 & 3
\end{bmatrix}

.

------------------------------------------------------------------------------
.

$\underline{\text{"Identidad"}}$

.

$\checkmark{Si $a_{ij}$ = 0 , $\forall_{ij} \neq j \ \land $ $a_{ij}$ = 1 , $\forall_{ij} = j}$

.

$\bullet{\text{"Entonces A se llama I"}}$

.

$\blacktriangle{\text{"EJEMPLO:"}}$

.

\begin{bmatrix}
1 & 0 & 0\\
0 & 1 & 0\\
0 & 0 & 1
\end{bmatrix}

.

------------------------------------------------------------------------------

$\underline{\text{"Matriz Simétrica"}}$

.

$\bullet{\text{"Si $A = A^T$ entonces $A$ se llama simétrica"}}$

.

$\blacktriangle{\text{"EJEMPLO:"}}$

.

$A=$
$\begin{bmatrix}
1 & 2\\
3 & 5
\end{bmatrix}$

.

$A^T=$
$\begin{bmatrix}
1 & 3\\
2 & 5
\end {bmatrix}$

------------------------------------------------------------------------------

$\underline{\text{"Antisimétrica"}}$

.

$\blacktriangle{\text{"EJEMPLO:"}}$

.

$A=$
$\begin{bmatrix}
1 & 3 & 5\\
-3 & -1 & 6\\
-5 & -6 & 2
\end {bmatrix}$

.

$A^T=$
$\begin{bmatrix}
1 & -3 & -5\\
3 & -1 & 6\\
5 & 6 & 2
\end{bmatrix}$

.

$\bullet{\text{"$A \neq A^T$ entonces es antisimétrica"}}$

.

------------------------------------------------------------------------------

.

###$\underline{\text{"Operaciones elementales de fila"}}$

.

$\bullet{\text{"Se enfoca nuestra atención a una matriz $A_{mxn}$"}}$

.

$\Longrightarrow{\text{"Multiplicación de un escalar por una fila"}}$

.

$\Longrightarrow{\text{"Reemplazar la enésima fila de $A$ por la fila $r+c$ veces la fila $s$"}}$

$\underline{\text{"$s \neq r$"}}$

.

$\Longrightarrow{\text{"Intercambio de filas"}}$

.

------------------------------------------------------------------------------

.

$\bullet{\text{"Matemáticamente"}}$

.

$1) e(A)rj = c.Arj$

$\dashv{\forall_{j} = 1, 2, 3,...,n}$

.

$2) e(A)rj = Arj + cAsj$
$\dashv{\forall_{j} = 1, 2, 3,...,n}$

.

$3) e(A)rj = Asj$

$\dashv{e(A)sj = Arj}$

.

$\blacktriangle{\text{"EJEMPLO:"}}$

$A=$
$\begin{bmatrix}
3 & 4 & 1\\
2 & 4 & -1\\
0 & 2 & -3
\end{bmatrix}$

.


$1) A1j = [3, 4, 1]$

$= 3 [3, 4, 1]$

$= [9, 12, 3]$

.

$e(A3j) = 3A3j$

.

$2) e(A2j) = A2j + (-1)A1j$

$e(A2j) = A2j + (-2)[1, -2, 3]$

$= [2, 4, 1] + [-2, 4, -6]$

$= [0, 8, -5]$

.

$3) e(A)rj = Asj$

$e(A)sj = Arj$

.

$\blacktriangle{\text{"EJEMPLO:"}}$

.

$A=$
$\begin{bmatrix}
1 & -2 & 3\\
2 & 4 & 1\\
0 & 3 & 7
\end{bmatrix}$

.

$1)A1j = [1, -2, 3]$

$e(A1j) = 3[1, -2, 3]$

$e(A1j) = [3, -6, 9]$

.

$\blacktriangle{\text{"Realizar:"}}$

$e(A3j) = 3A3j$

.

$2) e(A2j) = A2j + (-1)A1j$

$e(A2j) = A2j + (-2)[1, -2, 3]$

$= [2, 4, 1] + [-2, 4, -6]$

$= [0, 8, -5]$

------------------------------------------------------------------------------

.

$\blacktriangle{\text{"Realizar:"}}$

.

$e(A3j) = A3j + (-1)A2j$

.

$\bullet{\text{"Definicion"}}$


Si tenemos dos matrices A y B de dimensiones mxn compuestas de números reales, podemos decir que la matriz B es equivalente a la matriz A en términos de filas si B se obtiene a través de una serie de operaciones elementales de filas aplicadas a la matriz A.

.
$\dashv{A \simeq B}$


.

$\underline{\text{"Una matriz $R_{mxn}$ se llama reducida de filas si:"}}$

.

$\Longrightarrow{\text{"El primer elemento $\neq$ 0 de cada fila no nula es 1."}}$

.

$\Longrightarrow{\text{"Cada columna de $R$ que tiene este primer elemento 1 tiene sus otros elementos $\neq$ 0"}}$

.

$A \simeq B_1 \simeq B_2 ... \simeq B = R$

.

$\blacktriangle{\text{"EJEMPLO:"}}$

.

$R=$
$\begin{bmatrix}
0 & 1 & 0 & 5\\
1 & 0 & 0 & -1\\
0 & 0 & 1 & 2
\end{bmatrix}$
$\simeq$
$\begin{bmatrix}
1 & 0 & 0 & -1\\
0 & 1 & 0 & 5\\
0 & 0 & 1 & 2
\end{bmatrix}$

.

$2) e(Arj) = Arj + cAsj , \forall{j} = 1, 2,...n$

.

$\blacktriangle{\text{"Fórmula: Fila Nueva = Fila Antigua "}}$

.

------------------------------------------------------------------------------

.

$\bullet{\text{"Ejercicio: Transformar"}}$

.

$A=$
$\begin{bmatrix}
4 & 2 & 1 & 1\\
-1 & 9 & 4 & 2\\
-2 & 3 & 5 & 6
\end{bmatrix}$
$\simeq$
$\begin{bmatrix}
1 & 0 & 0 & r_{14}\\
0 & 1 & 0 & r_{24}\\
0 & 0 & 1 & r_{34}
\end{bmatrix}$

.

------------------------------------------------------------------------------

.
$\bullet{\text{"Matriz Reducida"}}$

.

Definición: Una matriz $R_{mxn}$ se llama matriz reducida, escalón por filas si y solo si:

.

$\Longrightarrow{\text{"$R$ es reducida."}}$

.
$\Longrightarrow{\text{"Toda la fila de $R$ que tiene todos sus elementos ceros (fila nula) está debajo de todas las filas no nulas"}}$

.

$\Longrightarrow{\text{"Si las filas 1, 2,...,r son las filas no nulas de $R$, y si el primer elemento no cero de la fila $i$ esta en la columna $K_i , i = 1,2,...,r$ entonces $K_1 < K_2 < ... < K_r$."}}$

.

$A → B_1 → B_2 → ... → B → R$

.

$\blacktriangle{\text{"EJEMPLO:"}}$

.

$A=$

$\begin{bmatrix}
2 & 4 & 3 & 4 & 2\\
3 & 5 & 4 & 9 & 3\\
3 & 4 & 5 & 6 & 7\\
8 & 6 & 6 & 9 & 3
\end{bmatrix}$
$\simeq$
$\begin{bmatrix}
1 & 1 & 1 & 1 & 1\\
0 & 1 & 1 & 1 & 1\\
0 & 0 & 0 & 0 & 0\\
0 & 0 & 0 & 0 & 0
\end{bmatrix}$

.

$\dashv{\text{Definición: Sea $A_{mxn}$ sobre $K$, si de $A_{mxn}$ obtenemos la $R$ escalonada}}$

.

------------------------------------------------------------------------------

.

1° Rango de $A=$ filas no nulas de $R$

.

$\underline{\text{"Operaciones con matrices"}}$

### SUMA

$$A_{mxn} + B_{mxn} = C_{mxn}$$

$\blacktriangle{\text{"EJEMPLO:"}}$


$A=$
$\begin{bmatrix}
1 & 2 & 3\\
-1 & -2 & 0
\end{bmatrix}$

.

$B=$
$\begin{bmatrix}
0 & 1 & -3\\
3 & 2 & 1
\end{bmatrix}$

.

$A+B=$
$\begin{bmatrix}
1 & 3 & 0\\
2 & 0 & 1
\end{bmatrix}$

.

------------------------------------------------------------------------------

.

$\underline{\text{"Producto de una matriz por un escalar"}}$

.

$C * A_{mn} = D_{mxn}$

.

$\blacktriangle{\text{"EJEMPLO:"}}$

.


$3$
$\begin{bmatrix}
1 & 2 & 3\\
-1 & -2 & 0
\end{bmatrix}$
$=$
$\begin{bmatrix}
3 & 6 & 9\\
-3 & -6 & 0
\end{bmatrix}$

.

------------------------------------------------------------------------------

.

$\underline{\text{"Producto de Matrices"}}$

.

$$A_{mxd} * B_{dxn} = C_{mxn}$$

$\forall{i} = 1,2,3,...,m$

$\forall{j} = 1,2,3,...,d$

$\forall{K} = 1,2,3,...,n$

.

$AB = [a_{2j}][b_{jK}] = [c_{iK}]$

.

$\blacktriangle{\text{"EJEMPLO:"}}$

.

$A=$
$\begin{bmatrix}
2 & 1 & 5\\
1 & 3 & 2
\end{bmatrix}$

.

$B=$
$\begin{bmatrix}
3 & 4\\
-1 & 2\\
2 & 1
\end{bmatrix}$

.

$A$x$B=$
$\begin{bmatrix}
15 & 15\\
4 & 12
\end{bmatrix}$

.

------------------------------------------------------------------------------

.

$\underline{\text{"Inversion de Matrices"}}$

.

$\dashv{\text{Definición: Sea $A_{n}$ una matriz cuadrada que opera sobre los $R$; si existe una matriz $B_{n}$ cuadrada tal que $AB = BA = I$}}$

.

$\dashv{\text{A la matriz $B$ se dice que es inversa de $A$ y $A$ es una matriz inversible; por lo que:}}$

.

$$B=A^{-1}$$

.

$\blacktriangle{\text{"Entonces"}}$

.

$$AA^{-1}=A^{-1}A=I$$

.

$\blacktriangle{\text{"Corolario"}}$

.

$A^{-1}$ es la inversa de $A$ y $A$ es la inversa de $A^{-1}$

.

$\blacktriangle{\text{"Teorema"}}$

.

Si $A$ es inversible entonces $(A^{-1})^{-1}=A$

.

$\blacktriangle{\text{"Teorema"}}$


.

$\dashv{\text{Si $A$ y $B$ son inversibles entonces su producto es inversible y además: $(AB)$ también es inversible y además:$$(AB)^{-1}=B^{-1}A^{-1}$$}}$


.

------------------------------------------------------------------------------

.

$\blacktriangle{\text{"Demostración"}}$

.

$$(AB)(AB)^{-1}=ABB^{-1}A^{-1}$$
$$=AIA^{-1}$$
$$=AA^{-1}$$
$$=I$$

.

$\dashv{\text{Si dos matrices son inversibles, el producto es inversible}}$

.

$\blacktriangle{\text{"EJEMPLO:"}}$

.

$A=$
$\begin{bmatrix}
2 & -1\\
1 & 3
\end{bmatrix}$
$\simeq$
$\begin{bmatrix}
2 & -1 & 1 & 0\\
1 & 3 & 0 & 1
\end{bmatrix}$
$\simeq$
$\begin{bmatrix}
1 & 3 & 0 & 1\\
2 & -1 & 1 & 0
\end{bmatrix}$
$\simeq$
$\begin{bmatrix}
1 & 3 & 0 & 1\\
0 & -7 & 1 & -2
\end{bmatrix}$
$\simeq$
$\begin{bmatrix}
1 & 3 & 0 & 1\\
0 & 1 & -1/7 & 2/7
\end{bmatrix}$
$\simeq$
$\begin{bmatrix}
1 & 0 & 3/7 & 1/7\\
0 & 1 & -1/7 & 2/7
\end{bmatrix}$

.

$\blacktriangle{\text{"entonces $A$ es inversible"}}$

.

$\blacktriangle{\text{"Nota: Si $R \neq I$ no ha inversa"}}$

.

------------------------------------------------------------------------------

.

$\underline{\text{"Matriz Ortogonal"}}$

.

Si $AA^{T} = D$

$A$ es Ortogonal

.

------------------------------------------------------------------------------

.

$\underline{\text{"Matriz Ortonormal"}}$

.

Si $AA^{T} = I$

$A$ es Ortonormal

.

------------------------------------------------------------------------------

.

$\underline{\text{"Determinantes"}}$

.

$\dashv{\text{Definición El determinante de una función es definida en la siguiente forma:}}$

.

$$detA \equiv |A|$$

.

$\dashv{\text{El determinante de una matriz $A$ de orden $n^{-1}$ se obtiene al eliminar la fila $i$ y la columna $j$ de la matriz original. Estos determinantes, de dimensiones más pequeñas que la matriz $A$, se conocen como menores. Los elementos $a_{ij}$ pueden corresponder a elementos de una fila o columna en particular.:}}$


.

$\blacktriangle{\text{"EJEMPLO:"}}$

.

$\blacktriangle{\text{"Matriz de Orden 2 (menor orden de todos)"}}$

.

$|A|=$
$\begin{bmatrix}
a_{11} & a_{12}\\
a_{21} & a_{22}
\end{bmatrix}$
$= a_{11} a_{22} - a_{21}a_{12} $

.

$\blacktriangle{\text{"Matriz de Orden 3"}}$


.

$|A_3|=$
$\begin{bmatrix}
a_{11} & a_{12} & a_{13}\\
a_{21} & a_{22} & a_{23}\\
a_{31} & a_{32} & a_{33}
\end{bmatrix}$
$=(-1)^{1+1} a_{11}$
$\begin{bmatrix}
a_{22} & a_{23}\\
a_{32} & a_{33}
\end{bmatrix}$
$+ (-1)^{2+1} a_{21}$
$\begin{bmatrix}
a_{12} & a_{13}\\
a_{32} & a_{33}
\end{bmatrix}$
$+ (-1)^{3+1} a_{31}$
$\begin{bmatrix}
a_{12} & a_{13}\\
a_{22} & a_{23}
\end{bmatrix}$

.

$\blacktriangle{\text{"EJEMPLO:"}}$

.

$A=$
$\begin{bmatrix}
1 & -1 & 1\\
1 & 2 & 1\\
1 & 3 & 2
\end{bmatrix}$
$=1$
$\begin{bmatrix}
2 & 1\\
3 & 2
\end{bmatrix}$
$-1$
$\begin{bmatrix}
-1 & 1\\
3 & 2
\end{bmatrix}$
$+1$
$\begin{bmatrix}
-1 & 1\\
2 & 1
\end{bmatrix}$
$=1-(-5)+(-3)=1+5-3=3$

.

------------------------------------------------------------------------------

.

##Resolucion Gauss Jordan

.

La resolución de matrices inversas es una herramienta importante en el álgebra lineal. El método de Gauss-Jordan es un algoritmo que nos permite encontrar la inversa de una matriz utilizando operaciones elementales de fila. A continuación, explicaremos el proceso paso a paso.

.

Dado una matriz cuadrada $A$, queremos encontrar su inversa $A^{-1}$. El método de Gauss-Jordan sigue los siguientes pasos:

.

  Escribe la matriz extendida $\left[ A \, | \, I \right]$, donde $I$ es la matriz identidad del mismo tamaño que $A$.
  Realiza operaciones elementales de fila para transformar la matriz $A$ en la matriz identidad $I$.
  
  .
  
  Estas operaciones elementales incluyen:        Intercambiar filas.
 Multiplicar una fila por un escalar no nulo.

 .

Sumar o restar una fila multiplicada por un escalar a otra fila.
Cuando la matriz $A$ se haya transformado en $I$, la matriz extendida sehabrá transformado en
La matriz $A^{-1}$ se encuentra en el lado derecho de la matriz extendida.

.

Ejemplo

.

Para ilustrar el método de Gauss-Jordan, consideremos la matriz $A$ siguiente:

.

$[
A = \begin{bmatrix}
2 & 1 \\
4 & 3 \\
\end{bmatrix}
]$

.

Siguiendo los pasos del método, escribimos la matriz extendida $\left[ A \, | \, I \right]$:

.

$[
\begin{bmatrix}
2 & 1 & | & 1 & 0 \\
4 & 3 & | & 0 & 1 \\
\end{bmatrix}
]$

.

Aplicamos operaciones elementales de fila para transformar la matriz $A$ en $I$:

.

$[
\begin{bmatrix}
1 & \frac{1}{2} & | & \frac{1}{2} & 0 \\
0 & 1 & | & -1 & 1 \\
\end{bmatrix}
]$

.

$[
\begin{bmatrix}
1 & 0 & | & 2 & -1 \\
0 & 1 & | & -1 & 1 \\
\end{bmatrix}
]$

.

Finalmente, la matriz extendida se ha transformado en $\left[ I \, | \, A^{-1} \right]$:

.

$[
\begin{bmatrix}
1 & 0 & | & 2 & -1 \\
0 & 1 & | & -1 & 1 \\
\end{bmatrix}
]$

.

Por lo tanto, la matriz inversa de $A$ es:

.

$[
A^{-1} = [
\begin{bmatrix}
1 & 0 & | & 2 & -1 \\
0 & 1 & | & -1 & 1 \\
\end{bmatrix}
]$

.

------------------------------------------------------------------------------

.

##Método de resolución: Matriz inversa y Eliminación Gaussiana

.

Existen varios métodos para resolver sistemas de ecuaciones lineales. Dos de ellos son el método de la matriz inversa y el método de eliminación gaussiana.

.

###Método de la matriz inversa

.

Si tenemos un sistema de ecuaciones lineales en forma matricial $AX = B$, donde $A$ es la matriz de coeficientes, $X$ es el vector columna de incógnitas y $B$ es el vector columna de términos constantes, podemos utilizar la matriz inversa para resolver el sistema. El método consiste en los siguientes pasos:

.

 Calcular el determinante de la matriz de coeficientes $A$. Si el determinante es igual a cero, el sistema no tiene solución única y no podemos utilizar este método.

.

 Calcular la matriz inversa de $A$ utilizando la fórmula $A^{-1} = \frac{1}{\det(A)} \cdot \text{Adj}(A)$, donde $\text{Adj}(A)$ es la matriz adjunta de $A$.

.

Multiplicar ambos lados de la ecuación $AX = B$ por $A^{-1}$ para obtener la solución: $X = A^{-1}B$.

.

###Método de eliminación gaussiana

.

El método de eliminación gaussiana es un método de resolución sistemático que transforma el sistema de ecuaciones lineales en un sistema equivalente más simple. Los pasos del método son los siguientes:

.

Escribir el sistema de ecuaciones en forma matricial $AX = B$, donde $A$ es la matriz de coeficientes, $X$ es el vector columna de incógnitas y $B$ es el vector columna de términos constantes.

.

 Realizar operaciones elementales de fila para transformar la matriz $A$ en una forma escalonada reducida.

.

 Aplicar las mismas operaciones elementales de fila a la matriz $B$.
 Despejar las incógnitas a partir de la forma escalonada reducida de la matriz $A$ y obtener la solución del sistema.

.

Ambos métodos, la matriz inversa y la eliminación gaussiana, proporcionan soluciones para sistemas de ecuaciones lineales. Sin embargo, el método de eliminación gaussiana es más utilizado en la práctica debido a su eficiencia computacional y su capacidad para manejar sistemas grandes.

.

------------------------------------------------------------------------------

.

##Eliminación de Gauss-Jordan

.

La eliminación de Gauss-Jordan es un método de resolución sistemático utilizado para transformar un sistema de ecuaciones lineales en forma matricial a una forma escalonada reducida. Este método permite obtener la solución del sistema de manera directa. Los pasos principales son los siguientes:

.

Escribir el sistema de ecuaciones en forma matricial $AX = B$, donde $A$ es la matriz de coeficientes, $X$ es el vector columna de incógnitas y $B$ es el vector columna de términos constantes.

.

Agregar la matriz identidad $I$ del mismo tamaño que $A$ a la derecha de la matriz $A$, de manera que se obtenga la matriz aumentada $[A\,|\,I]$.

.

Aplicar operaciones elementales de fila para transformar la matriz aumentada $[A\,|\,I]$ en una forma escalonada reducida. Estas operaciones elementales incluyen el intercambio de filas, la multiplicación de filas por una constante no nula y la suma/resta de filas.

.

Al finalizar las operaciones elementales, la parte izquierda de la matriz aumentada $[A\,|\,I]$ se convertirá en la matriz identidad $I$, y la parte derecha representará la matriz inversa de $A$. Si la matriz $A$ es no invertible, la parte izquierda no se convertirá en la matriz identidad y se llegará a una forma escalonada reducida con filas nulas.

.

Si se desea encontrar la solución particular del sistema, se puede multiplicar la parte derecha de la matriz aumentada $[A\,|\,I]$ por el vector columna $B$, lo cual dará la solución $X$.

.

La eliminación de Gauss-Jordan es un método eficiente para resolver sistemas de ecuaciones lineales, ya que directamente se obtiene la solución sin necesidad de etapas adicionales. Sin embargo, es importante tener en cuenta que si la matriz $A$ es singular (no invertible), el sistema puede tener múltiples soluciones o ser incompatible.

.

Consideremos el siguiente sistema de ecuaciones lineales:

.

$[
\begin{aligned}
2x + 3y - z &= 7 \\
x - 2y + 2z &= -1 \\
3x + y - 3z &= 9 \\
\end{aligned}
]$

.

Para resolver este sistema utilizando la eliminación de Gauss-Jordan, podemos escribirlo en forma matricial:

.

$[
\begin{bmatrix}
2 & 3 & -1 \\
1 & -2 & 2 \\
3 & 1 & -3 \\
\end{bmatrix}
\begin{bmatrix}
x \\
y \\
z \\
\end{bmatrix}
=
\begin{bmatrix}
7 \\
-1 \\
9 \\
\end{bmatrix}
]$

.

Agreguemos la matriz identidad $I$ a la derecha de la matriz de coeficientes y obtendremos la matriz aumentada $[A\,|\,I]$:

.

$[
\begin{bmatrix}
2 & 3 & -1 & | & 1 & 0 & 0 \\
1 & -2 & 2 & | & 0 & 1 & 0 \\
3 & 1 & -3 & | & 0 & 0 & 1 \\
\end{bmatrix}
]$

.

Aplicando operaciones elementales de fila, llevamos la matriz aumentada a forma escalonada reducida:

.

$[
\begin{bmatrix}
1 & 0 & 0 & | & 1 & -1 & 1 \\
0 & 1 & 0 & | & 2 & -2 & 1 \\
0 & 0 & 1 & | & -1 & 1 & -1 \\
\end{bmatrix}
]$

.

De esta forma, hemos obtenido la matriz identidad en la parte izquierda y en la parte derecha tenemos la solución del sistema. Por lo tanto, la solución es:

.

$[
\begin{aligned}
x &= 1 \\
y &= 2 \\
z &= -1 \\
\end{aligned}
]$

.

Así, hemos resuelto el sistema de ecuaciones utilizando el método de eliminación de Gauss-Jordan.

.

##Regla de Cramer y Discusión de Sistemas de Ecuaciones Lineales

.

La Regla de Cramer es un método utilizado para resolver sistemas de ecuaciones lineales (SEL) mediante el uso de determinantes. Permite encontrar la solución de un sistema en términos de las variables individuales, siempre que el sistema sea compatible determinado.

.

Consideremos un SEL con $n$ incógnitas y $n$ ecuaciones:

.

$[
\begin{aligned}
a_{11}x_1 + a_{12}x_2 + \ldots + a_{1n}x_n &= b_1 \\
a_{21}x_1 + a_{22}x_2 + \ldots + a_{2n}x_n &= b_2 \\
\vdots \\
a_{n1}x_1 + a_{n2}x_2 + \ldots + a_{nn}x_n &= b_n \\
\end{aligned}
]$

.

Podemos representar este sistema de ecuaciones en forma matricial como $AX = B$, donde $A$ es la matriz de coeficientes, $X$ es el vector columna de incógnitas y $B$ es el vector columna de términos constantes.

.

Para aplicar la Regla de Cramer, debemos calcular los determinantes de la matriz de coeficientes $A$ y de las matrices obtenidas al reemplazar cada columna de $A$ por el vector columna $B$.

.

Si el determinante de la matriz de coeficientes $A$ es diferente de cero, el sistema tiene solución única y podemos utilizar la Regla de Cramer para encontrar los valores de las variables. La solución se obtiene de la siguiente manera:
$[
x_i = \frac{{\det(A_i)}}{{\det(A)}}
]$
donde $A_i$ se obtiene al reemplazar la columna $i$ de $A$ por $B$.

.

Si el determinante de la matriz de coeficientes $A$ es cero, el sistema puede tener múltiples soluciones o ser incompatible.

.

Si al menos uno de los determinantes de las matrices $A_i$ es diferente de cero, el sistema es incompatible y no tiene solución única.

.

Si todos los determinantes de las matrices $A_i$ son cero, el sistema puede tener múltiples soluciones o no tener solución única. En este caso, es necesario utilizar métodos adicionales para determinar la naturaleza del sistema.

.

La Regla de Cramer es una herramienta útil para resolver sistemas de ecuaciones lineales y analizar su naturaleza. Sin embargo, su aplicación puede volverse costosa computacionalmente cuando el número de incógnitas es grande.

.

------------------------------------------------------------------------------

.

$\underline{\text{"Sistemas de ecuaciones"}}$

.

$\dashv{\text{Los sistemas de ecuaciones lineales en forma de matrices son una herramienta eficaz para resolver conjuntos de ecuaciones lineales. En este enfoque, las incógnitas y los coeficientes se representan mediante matrices. Por ejemplo, consideremos el siguiente sistema de ecuaciones lineales:}}$

.

\begin{cases}
2x+3y=8\\
4x-2y=2
\end{cases}

.

$\blacktriangle{\text{"Se puede representar matricialmente como:"}}$

.

\begin{bmatrix}
2 & 3 & x & 8\\
4 & -2 & y & 2
\end{bmatrix}

.

------------------------------------------------------------------------------

.

$\underline{\text{"Factorización LU"}}$

.

$\dashv{\text{La factorización LU es un método para descomponer una matriz en el producto de dos matrices: una matriz triangular inferior ($L$) y una matriz triangular superior ($U$).}}$

.

$\blacktriangle{\text{"EJEMPLO:"}}$

.

$A=$
$\begin{bmatrix}
2 & 1 & 3\\
4 & 0 & 2\\
1 & 3 & 1
\end{bmatrix}$

.

$\dashv{\text{La factorización LU de una matriz implica encontrar dos matrices, L y U, de tal manera que la matriz original A se pueda expresar como el producto de L y U, es decir, A = LU. La matriz L es una matriz triangular inferior con unos en la diagonal principal, mientras que la matriz U es una matriz triangular superior.}}$

.

$\blacktriangle{\text{"Después de aplicar el método de factorización LU a la matriz $A$, obtenemos:"}}$

.

$L=$
$\begin{bmatrix}
1 & 0 & 0\\
2 & 1 & 0\\
1/2 & 1 & 1
\end{bmatrix}$

.

$U=$
$\begin{bmatrix}
2 & 1 & 3\\
0 & -2 & -4\\
0 & 0 & -1
\end{bmatrix}$

.

------------------------------------------------------------------------------

.

-$$Espacios Vectoriales$$-

.
$\dashv{\text{Un espacio vectorial es un conjunto de objetos llamados vectores, que no está vacío y en el que se han definido dos operaciones: la suma y la multiplicación por un escalar (un número real). Estas operaciones deben cumplir diez axiomas que se aplican a todos los vectores u, v, y w en el espacio vectorial V, así como a todos los escalares α y β reales.}}$

.
$\blacktriangle{\text{"Llamamos $u + v$ a la suma de vectores en $V$, y $αv$ al producto de un número real α por un vector $v ∈ V$."}}$

.

------------------------------------------------------------------------------

.

$\blacktriangle{\text{"Axiomas"}}$

.

$\Longrightarrow{\text{$u+v ∈ V$}}$

.

$\Longrightarrow{\text{$u+v=v+u$}}$

.

$\Longrightarrow{\text{$(u+v)+w=u+(v+w)$}}$

.

$\Longrightarrow{\text{Existe un vector nulo $0_{V} ∈ V$ tal que $v+0_{V}=v$}}$

.

$\Longrightarrow{\text{Para cada $v$ en $V$, existe un opuesto $(-v) ∈ V$ tal que $v+(-v)=0_{V}$}}$

.

$\Longrightarrow{\text{$αv ∈ V$}}$

.

$\Longrightarrow{\text{$α(u+v)=αu+αv$}}$

.

$\Longrightarrow{\text{$(α+β)v=αv+βv$}}$

.

$\Longrightarrow{\text{$α(βv)=(αβ)v$}}$

.

$\Longrightarrow{\text{$1v=v$}}$

.

------------------------------------------------------------------------------

.

$\blacktriangle{\text{"Propiedades"}}$

.

$\Longrightarrow{\text{$0_{u}=0_{V}$}}$

.

$\Longrightarrow{\text{$α0_{V}=0_{V}$}}$

.

$\Longrightarrow{\text{$(-α)u=-(αu)$ En particular, para $α=1:(-1)u=-u$}}$

.

$\Longrightarrow{\text{$αu=0_{V} ⟹ α=0$  ó  $u=0_{V}$}}$

.

------------------------------------------------------------------------------

.

$\underline{\text{"Subespacios vectoriales"}}$

.

$\dashv{\text{Si tenemos un espacio vectorial V y un subconjunto no vacío W de V, entonces W se considera un subespacio de V si W, por sí mismo, es también un espacio vectorial que tiene las mismas operaciones de suma de vectores y multiplicación por un escalar definidas en V.}}$

.

$\blacktriangle{\text{"EJEMPLO:"}}$

.

$W=\{(x_{1},x_{2} ∈ R^{2}: x_{2}=3x_{1}\}$ ¿Es un subespacio vectorial de $R^{2}$?

.

$\dashv{\text{Primero analicemos el conjunto $W$. Son todos vectores de $R^{2}$ tales que la segunda componente es el triple de la primera:}}$

.

$$(x_{1},3x_{1})=x_{1}(1,3)$$

.

$\dashv{\text{$W$ es la recta que pasa por el origen y tiene vector director $(1,3)$, o sea la recta de ecuación $y=3x$}}$

.

$\dashv{\text{Para decidir si $W$ es un subespacio de $R^{2}$ habría que verificar que se cumplen los axiomas del 1 al 10. En este caso se *cumplen*.}}$

.

------------------------------------------------------------------------------

.

$\underline{\text{"Bases y Dimensiones"}}$

.

$\dashv{\text{En el contexto de un espacio vectorial o subespacio vectorial, se denomina base a un conjunto de vectores que es linealmente independiente y, al mismo tiempo, genera todo el espacio o subespacio en cuestión.}}$

.

------------------------------------------------------------------------------

.

$\blacktriangle{\text{Propiedades de las bases}}$

.

$\Longrightarrow{\text{Una base de $S$ es un sistema generador minimal de $S$ (lo más pequeño posible).}}$

.

$\Longrightarrow{\text{Además es un conjunto independiente maximal dentro de $S$ (lo más grande posible).}}$

.

$\Longrightarrow{\text{Una base de $S$ permite expresar todos los vectores de $S$ como combinación lineal de ella, de manera única para cada vector.}}$

.

$\blacktriangle{\text{"EJEMPLO:"}}$

.

-1. La base canónica de $R^{n}$-
$$e_{1}=(1,0,...,0)$$
$$e_{2}=(0,1,...,0)$$
$$...$$
$$e_{n}=(0,0,...,1)$$

.

$\Longrightarrow{\text{Son linealmente independientes porque forman un determinante no nulo.}}$

.

$\Longrightarrow{\text{Son sistema generador de $R^{n}$ porque todo vector $(a_{1},a_{2},...,a_{n})∈R^{n}$}}$

.

-2. Otra base de $R^{3}$ distinta de la canónica:- $(1,0,0),(1,1,0),(0,2,-3)$.

.

$\Longrightarrow{\text{Son linealmente independientes porque forman un determinante no nulo.}}$

.

$\Longrightarrow{\text{Son sistema generador de $R^{3}$ porque cualquier vector $(a,b,c)$ se puede poner como combinacion lineal de ellos. En efecto, dado $(a,b,c)$, buscamos $α,β$ y que satisfagan:}}$

.

$$(a,b,c)=α(1,0,0)+γ(0,2,-3)$$

.

$\blacktriangle{\text{Se obtiene un sistema:}}$

.

\begin{cases}
α+β=a\\
β+2γ=b\\
-3γ=c
\end{cases}

.

-3.* $(1,2,3), (4,5,6), (7,8,9)$ en $R^{3}$ *no forman base porque no son linealmente independientes (su determinante es nulo).-

.

-4. Base de un subespacio. En $R^{3}$, consideremos el subespacio* $S=$plano$XY$. *Veamos que los vectores* $(3,2,0), (1,-1,0)$ *forman una base de* $S$*.-

.

------------------------------------------------------------------------------

.

$\underline{\text{"Dimensión"}}$

.

$\dashv{\text{En un espacio vectorial o subespacio vectorial, todas las bases comparten la misma cantidad de vectores. A esta cantidad se le denomina dimensión del espacio o subespacio.}}$

.

$\blacktriangle{\text{"EJEMPLO:"}}$

.

$\Longrightarrow{\text{$R^{n}$ tiene dimension $n$, pues tiene una base de $n$ elementos.}}$

.

$\Longrightarrow{\text{$M_{2x2}$ ={matrices 2x2 con terminos reales} tiene dimensión 4. Una base de $M_{2x2}$ es:}}$

.

$\begin{bmatrix}
1 & 0\\
0 & 0
\end{bmatrix}$
$.$
$\begin{bmatrix}
0 & 1\\
0 & 0
\end{bmatrix}$
$.$
$\begin{bmatrix}
0 & 0\\
1 & 0
\end{bmatrix}$
$.$
$\begin{bmatrix}
0 & 0\\
1 & 0
\end{bmatrix}$
$.$
$\begin{bmatrix}
0 & 0\\
0 & 1
\end{bmatrix}$

.

$\Longrightarrow{\text{$P_{2}=${polinomios de grado <= 2 con coeficientes reales} tiene dimension 3. Una base de $P_{2}$ es, por ejemplo, la formada por los tres polinomios siguientes:}}$

.

$1+0x+0x^{2} , 0+x+0x^{2} , 0+0x+x^{2}$ (es decir, los polinomios $1, x, x^{2}$).

.

Otra base: $1+2x+3x^{2} , 4+x^2 , 3-x-5x^2$

.
------------------------------------------------------------------------------

.

$\blacktriangle{\text{Propiedades de la dimensión}}$

.
$\Longrightarrow{\text{Significado físico de la dimensión: los planos tienen dimensión 2, las rectas dimensión 1, el punto dimensión 0. El subespacio $\{0\}$ es el único que tiene dimensión 0.}}$

.

$\Longrightarrow{\text{La dimensión de un subespacio en $R^{n}$, coincide con el número de parámetros libres en su forma paramétrica.}}$

.

$\Longrightarrow{\text{Si $S$ y $T$ son subespacios y $S$ está contenido en $T$, entonces $dim S <= dim T$. Además, si se da la igualdad, $dim S = dim T$, ambos espacios han de coincidir.}}$

.

$\Longrightarrow{\text{El rango de una familia de vectores, es igual a la dimensión del subespacio que generan.
Es decir: si $v1,v2,. . . v_{n}$ generan un cierto subespacio $S$, y si el rango de dicho conjunto es $r$, entonces $dim S = r$. (Si un cierto conjunto de vectores tienen rango 2, entonces generan un plano; etc.)}}$

.

$\blacktriangle{\text{"EJEMPLO:"}}$

.

$\Longrightarrow{\text{En el espacio tridimensional ℝ³, consideremos el subespacio S generado por los vectores (1, 0, 2), (0, -1, -2), (3, 3, 3) y (2, 2, 0). Al observar que el rango de este conjunto, tanto si lo organizamos por filas como por columnas, es 3, podemos aplicar la propiedad 4 para concluir que la dimensión de S es 3. Sin embargo, dado que nos encontramos en ℝ³, según la propiedad... (la oración se corta en la pregunta original).}}$

.

------------------------------------------------------------------------------

.

$$-Conicas-$$

.
$\Longrightarrow{\text{Definición: El lugar geométrico de los puntos cuya relación de distancias a un punto y una recta fijos es constante recibe el nombre de sección cónica o simplemente cónica.}}$

.

\begin{cases}
Punto Fijo → Foco\\
Recta Fija → Directriz\\
Relación Constante → Excentricidad (e)
\end{cases}

.

$\blacktriangle{\text{*Excentricidad*}}$

.

$$e=\frac{c}{a}=\frac{\sqrt{a^2+b^2}}{a};e>1$$

.

------------------------------------------------------------------------------

.

$\underline{\text{"Categorías"}}$

.

$\checkmark{Si $e<1$, la cónica se llama *Elipse*}$

.

$\checkmark{Si $e=1$, la cónica se llama *Parábola*}$

.

$\checkmark{Si $e>1$, la cónica se llama *Hipérbola*}$

.

------------------------------------------------------------------------------

.

$\underline{\text{"Parábola"}}$

.

$\blacktriangle{\text{Ecuación de la parábola}}$

.

$\Longrightarrow{\text{*Foco a la derecha de directriz:*}}$

.

$$(y-k)^{2}=4a(x-h)$$

.

$\Longrightarrow{\text{*Directriz encima de foco*}}$

.

$$(x-h)^{2}=-4a(y-k)$$

.

$\Longrightarrow{\text{*Foco a la izquierda de directriz*}}$

.

$$(y-k)^{2}=-4a(x-h)$$

.

$\Longrightarrow{\text{*Foco encima de directriz*}}$

.

$$(x-h)^{2}=4a(y-k)$$

.

------------------------------------------------------------------------------

.

$\underline{\text{"Elipse"}}$

.

$\blacktriangle{\text{Ecuación de la elipse}}$

.

$$\frac{x^2}{a^2} + \frac{y^2}{b^2} = 1$$

.

$\Longrightarrow{\text{Si los focos fueran coordenadas (0,c) y (0,-c), el Eje Mayor estaría sobre el eje $y$ entonces la ec. sería:}}$

.

$$\frac{x^2}{b^2}+\frac{y^2}{a^2}=1$$

.

$\Longrightarrow{\text{*Ecs. de las directrices $D'D'$ y $DD$ respectivamente*}}$

.

$$x+\frac{a}{e}=0$$y$$x-\frac{a}{e}=0$$

.

$\Longrightarrow{\text{Se denomina *latus rectum* de la elipse a la cuerda perpendicular al eje mayor por uno de los focos, su longitud es $\frac{2b^{2}}{a}$}}$

.

$\Longrightarrow{\text{Si el centro de la elipse fuese el punto $(h,k)$ y el eje mayor tiene la dirección del eje $x$, la ecuación de la elipse seria igual a:}}$

.

$$\frac{(x-h)^2}{a^2}+\frac{(y-k)^2}{b^2}=1$$
→Eje mayor perpendicular al eje $x$
$$\frac{(x-h)^2}{b^2}+\frac{(y-k)^2}{a^2}=1$$
→Eje mayor perpendicular al eje $y$

.

$\Longrightarrow{\text{*Ecuacion general de la elipse*}}$

.

$$Ax^2+By^2+Dx+Ey+F=0$$

.

------------------------------------------------------------------------------

.

$\underline{\text{"Hipérbola"}}$

.

$\blacktriangle{\text{Ecuación de la hipérbola}}$

.

$$\frac{x^2}{a^2}-\frac{y^2}{b^2}=1$$

$$c^2-a^2=b^2$$

.
$\blacktriangle{\text{Focos tienen coordenadas}}$

$F(c,0)$ y $F'(-c,0)$

*Distancia entre $F$ y $F'$ es igual a $2a$*

.
$\blacktriangle{\text{Ecuaciones directrices DD'}}$

$$x=±\frac{a}{e}$$

.

$\blacktriangle{\text{Focos están sobre eje $x$}}$

$$y=±\frac{a}{e}$$

.

$\blacktriangle{\text{Focos están sobre eje $y$}}$

*Ecs. asíntotas*

$$y=±\frac{b}{a}x$$

.

$\blacktriangle{\text{Cuando el eje real es $x$}}$

$$y=±\frac{a}{b}x$$

.

$\blacktriangle{\text{Cuando el eje real es $y$}}$

.

$\blacktriangle{\text{Si el centro de la hipérbola es el pto coordenadas (h,k):}}$

$$\frac{(x-h)^2}{a^2}-\frac{(y-k)^2}{b^2}=1$$

.

$\blacktriangle{\text{Eje real paralelo al eje $x$}}$

$$\frac{(y-k)^2}{a^2}-\frac{(y-k)^2}{b^2}=1$$

.

$\blacktriangle{\text{Eje real paralelo al eje $y$}}$

.

------------------------------------------------------------------------------

.

$\blacktriangle{\text{Forma General de la Ec. de la Hipérbola}}$

.

$$Ax^2-By^2+Dx+Ey+F=0→$$ siendo $A$ y $B$ del mismo signo.

.

$$-Transformaciones Lineales y Vectores Propios-$$

.

$\underline{\text{"Transformaciones Lineales"}}$

.

$\Longrightarrow{\text{Una transformación lineal es una función que opera entre dos espacios vectoriales, denotados como V y W. Esta función asigna vectores de V a vectores de W. Sin embargo, no todas las funciones que transforman vectores de V a vectores de W son consideradas transformaciones lineales. Para que una función sea una transformación lineal, debe cumplir ciertas condiciones específicas.}}$

.

$F: V→W$ es una transformación lineal ssi:

.

$\checkmark{$F(u+v)=F(u)+F(v)$ , $ ∀ $ $u,v ∈ V$}$

.

$\checkmark{$F(k,v)=k,F(v)$ , $∀v∈V$ , $∀k∈R$}$

.


------------------------------------------------------------------------------

.

$\blacktriangle{\text{Propiedades de una Transformacion Lineal}}$

.

-Propiedad 1-

.

$\Longrightarrow{\text{La imagen del vector nulo del dominio $0_{v}$ es el vector nulo del codominio $0_{w}$:
$$T(0_V)=0_w$$}}$

.

-Propiedad 2-

.

$\Longrightarrow{\text{La imagen del vector $-v$ es igual al opuesto de la imagen de $v$:
$$T(-v)=-T(v)$$}}$

.

-Propiedad 3-

.

$\Longrightarrow{\text{Consideremos $r$ vectores del espacio vectorial $V$:
$$v_1,v_2,...,v_r ∈ V$$}}$

.

$\blacktriangle{\text{Tomemos una combinación lineal en el dominio:}}$

.

$$α_1v_1+α_2v_2+α_3v_3+...+α_rv_r$$

.

$\blacktriangle{\text{Donde $α_i ∈ R$}}$

.

$\Longrightarrow{\text{Si aplicamos la transformación lineal $F$ de $V$ a $W$, teniendo en cuenta las propiedades enunciadas en la definición, resulta:}}$

.

$$F(α_1v_1+α_2v_2+α_3v_3+...+α_rv_r)=α_1F(v_1)+α$$

.

$\Longrightarrow{\text{Es decir que una transformación lineal <\<transporta\>> combinaciones lineales de $V$ a $W$, conservando los escalares de la combinación lineal.}}$

.

$\blacktriangle{\text{"EJEMPLO:"}}$

.

Sea $$T(1,0)=(2,1,-1)$$
$$T(0,1)=(1,-1,0)$$

encuentre $T$
$$R^2→R^3$$
$$(x,y)→T(x,y)=?$$

.

$$B\{v_1, v_2\} → $$
$B=$
$\begin{cases}
\begin{bmatrix}
1\\
0
\end{bmatrix}
,
\begin{bmatrix}
0\\
1
\end{bmatrix}
\end{cases}$

.

$v_1=α_1v_2+α_2v_2$

$v=α$
$\begin{bmatrix}
1\\
0
\end{bmatrix}$
$+α_2$
$\begin{bmatrix}
0\\
1
\end{bmatrix}$

$$x=α_1$$
$$y=α_2$$

$T(\vec{v})=T$
$\left(
    \begin{bmatrix}
    x\\
    y
    \end{bmatrix}
\right)$
$=$
$α_1T$
$\left(
  \begin{bmatrix}
  1\\
  0
  \end{bmatrix}
\right)$
$+α_2T$
$\left(
  \begin{bmatrix}
  0\\
  1
  \end{bmatrix}
\right)$

$T$
$\left(
  \begin{bmatrix}
  x\\
  y
  \end{bmatrix}
\right)$
$=$
$α_1$
$\begin{bmatrix}
2\\
1\\
-1
\end{bmatrix}$
$+α_2$
$\begin{bmatrix}
1\\
-1\\
0
\end{bmatrix}$

$T$
$\left(
  \begin{bmatrix}
  x\\
  y
  \end{bmatrix}
\right)$
$=x$
$\begin{bmatrix}
2\\
1\\
1
\end{bmatrix}$
$+y$
$\begin{bmatrix}
1\\
-1\\
0
\end{bmatrix}$
$=$
$\begin{bmatrix}
2x+4\\
x-y\\
-x
\end{bmatrix}$

.

------------------------------------------------------------------------------

.

##Diagonalización de Matrices

.

La diagonalización de matrices es un proceso importante en el álgebra lineal que consiste en descomponer una matriz en una forma más simple, donde la matriz resultante es diagonal. Esta descomposición facilita el cálculo y el análisis de la matriz original.

.

###Definición

.

Una matriz cuadrada $A$ de tamaño $n \times n$ es diagonalizable si existe una matriz invertible $P$ y una matriz diagonal $D$ tal que se cumple la siguiente igualdad:

.

$[
A = PDP^{-1}
]$

.

donde $D$ es una matriz diagonal cuyos elementos están en la diagonal principal y los elementos fuera de la diagonal principal son todos cero. La matriz $P$ está formada por los vectores propios de $A$ como columnas.

.

###Proceso de Diagonalización

.

El proceso de diagonalización de una matriz implica los siguientes pasos:

.

Encontrar los valores propios de la matriz $A$ resolviendo la ecuación característica $\text{det}(A - \lambda I) = 0$.

.

Para cada valor propio $\lambda$, encontrar los vectores propios correspondientes resolviendo el sistema de ecuaciones homogéneo $(A - \lambda I) \mathbf{v} = \mathbf{0}$.

.

Formar la matriz $P$ con los vectores propios encontrados, donde cada vector propio es una columna de la matriz.

.

Calcular la matriz inversa de $P$.

.

Formar la matriz diagonal $D$ colocando los valores propios en la diagonal principal y ceros en los demás lugares.

.

Verificar la igualdad $A = PDP^{-1}$ para confirmar la diagonalización.

.

###Aplicaciones

.

La diagonalización de matrices tiene varias aplicaciones en el álgebra lineal y otras áreas:

.

Simplifica el cálculo de potencias de matrices. Si una matriz $A$ es diagonalizable, entonces $A^k = PD^kP^{-1}$, donde $D^k$ es una matriz diagonal con los valores propios elevados a la potencia $k$ en la diagonal principal.

.

Permite analizar y comprender las propiedades y el comportamiento de una matriz. La diagonalización revela información sobre la estructura y los vectores propios asociados a la matriz.

.

Se utiliza en la resolución de sistemas de ecuaciones diferenciales lineales y en el estudio de problemas de valor inicial en matemáticas aplicadas.

.

##Teorema de Cayley-Hamilton

.

El Teorema de Cayley-Hamilton es un resultado fundamental en el álgebra lineal que establece una relación entre una matriz y su polinomio característico. Este teorema establece que toda matriz satisface su propio polinomio característico.

.

###Enunciado

.

Sea $A$ una matriz cuadrada de tamaño $n \times n$ con coeficientes en un campo o anillo conmutativo. El Teorema de Cayley-Hamilton establece que el polinomio característico $p_A(\lambda)$ de la matriz $A$ satisface la siguiente igualdad:

.

$[
p_A(A) = 0
]$

.

donde $p_A(A)$ es la matriz resultante al evaluar el polinomio característico $p_A(\lambda)$ en la matriz $A$, y $0$ es la matriz nula de tamaño $n \times n$.

.

###Implicaciones

.

El Teorema de Cayley-Hamilton tiene varias implicaciones importantes:

.

Permite calcular potencias de una matriz de manera más eficiente. En lugar de elevar la matriz a una potencia $k$ utilizando multiplicaciones repetidas, se puede utilizar el polinomio característico para simplificar el cálculo.

.

Proporciona una prueba de que cualquier matriz satisface una ecuación polinómica. Esto es útil para demostrar propiedades y realizar cálculos algebraicos relacionados con matrices.

.

Tiene aplicaciones en el estudio de sistemas lineales y en la diagonalización de matrices. Permite determinar propiedades y comportamientos de una matriz a partir de su polinomio característico.

.

------------------------------------------------------------------------------

.

###Demostración

.

La demostración del Teorema de Cayley-Hamilton es un resultado avanzado y requiere conocimientos más profundos de álgebra lineal y teoría de matrices. Se basa en conceptos como la descomposición de Jordan y la teoría de módulos.

.

###Ejemplo

.

Considera una matriz $A$ de tamaño $2 \times 2$:

.

$[
A = \begin{bmatrix}
a & b \\
c & d \\
\end{bmatrix}
]$

.

El polinomio característico de $A$ es:

.

$[
p_A(\lambda) = \lambda^2 - (a+d)\lambda + (ad - bc)
]$

.

De acuerdo con el Teorema de Cayley-Hamilton, evaluamos este polinomio en la matriz $A$:

.

$[
p_A(A) = A^2 - (a+d)A + (ad - bc)I = 0
]$

.

donde $I$ es la matriz identidad de tamaño $2 \times 2$. Esta igualdad muestra cómo la matriz $A$ satisface su propio polinomio característico.

.

------------------------------------------------------------------------------

.

##Vectores y Valores Propios

.

En el álgebra lineal, los vectores y valores propios son conceptos fundamentales asociados a las transformaciones lineales y las matrices. Estos conceptos nos permiten entender cómo los vectores se comportan bajo la acción de una transformación y qué valores escalares son especialmente importantes para dicha transformación.

.

###Vectores Propios

.

Dada una transformación lineal $T$ de un espacio vectorial $V$ a sí mismo, un vector propio (también conocido como autovector) de $T$ es un vector no nulo $\mathbf{v}$ en $V$ que satisface la siguiente ecuación:

.

$[
T(\mathbf{v}) = \lambda \mathbf{v}
]$

.

donde $\lambda$ es un escalar llamado valor propio (también conocido como autovalor) asociado al vector propio $\mathbf{v}$. Esta ecuación indica que la transformación $T$ simplemente escala el vector $\mathbf{v}$ por un factor $\lambda$. Los vectores propios representan direcciones especiales en el espacio que no cambian su dirección bajo la transformación lineal.

.

###Ecuación Característica

.

La ecuación característica se utiliza para encontrar los valores propios de una transformación lineal o una matriz. Supongamos que tenemos una matriz $A$ de tamaño $n \times n$ asociada a una transformación lineal. La ecuación característica se define como:

.

$[
\text{det}(A - \lambda I) = 0
]$

.

donde $\lambda$ es el valor propio desconocido y $I$ es la matriz identidad del mismo tamaño que $A$. La solución de esta ecuación proporciona los valores propios posibles para la transformación lineal o la matriz.

.

###Polinomio Característico

.

El polinomio característico es el polinomio obtenido al expandir la ecuación característica. Supongamos que el tamaño de la matriz $A$ es $n \times n$. El polinomio característico se define como:

.

$[
\text{det}(A - \lambda I) = (-1)^n (\lambda^n + c_{n-1}\lambda^{n-1} + \ldots + c_1 \lambda + c_0)
]$

.

donde $c_{n-1}, c_{n-2}, \ldots, c_1, c_0$ son los coeficientes del polinomio. Los valores propios son las raíces del polinomio característico.

.

###Propiedades

.

Los vectores y valores propios tienen varias propiedades importantes:

.

Los vectores propios correspondientes a valores propios distintos son linealmente independientes.

.

Si una matriz es diagonalizable, se puede expresar como una combinación lineal de sus vectores propios.

.

Los valores propios pueden ser reales o complejos.

.

La multiplicidad de un valor propio es el número de veces que aparece como raíz en el polinomio característico.

.

Estas propiedades nos permiten analizar y comprender la estructura y el comportamiento de las transformaciones lineales y las matrices a través de sus vectores y valores propios.

In [1]:
#Codigo para multiplicar matrices
import numpy as np

# Definir las matrices
matriz1 = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])

matriz2 = np.array([[1, 1, 2],
                    [1, 1, 5],
                    [1, 7, 1]])

# Multiplicar las matrices
resultado = np.dot(matriz1, matriz2)

# Imprimir el resultado
print(resultado)

[[ 6 24 15]
 [15 51 39]
 [24 78 63]]


In [2]:
#Transpocicionde matrices codigo python
def transponer_matriz(matriz):
    filas = len(matriz)
    columnas = len(matriz[0])

    matriz_transpuesta = [[0 for _ in range(filas)] for _ in range(columnas)]

    for i in range(filas):
        for j in range(columnas):
            matriz_transpuesta[j][i] = matriz[i][j]

    return matriz_transpuesta

# Ejemplo de uso
matriz_original = [[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]]

matriz_transpuesta = transponer_matriz(matriz_original)

# Imprimir matriz original
print("Matriz original:")
for fila in matriz_original:
    print(fila)

# Imprimir matriz transpuesta
print("\nMatriz transpuesta:")
for fila in matriz_transpuesta:
    print(fila)

Matriz original:
[1, 2, 3]
[4, 5, 6]
[7, 8, 9]

Matriz transpuesta:
[1, 4, 7]
[2, 5, 8]
[3, 6, 9]


In [3]:
import numpy as np
# Codigo para inverit matrices 2x2
# Definir una matriz de ejemplo
matrix = np.array([[1, 2], [3, 4]])

# Calcular la matriz inversa
inverse_matrix = np.linalg.inv(matrix)

print("Matriz original:")
print(matrix)

print("Matriz inversa:")
print(inverse_matrix)

Matriz original:
[[1 2]
 [3 4]]
Matriz inversa:
[[-2.   1. ]
 [ 1.5 -0.5]]


In [4]:
#suma de matrices codigo
def suma_matrices(matriz1, matriz2):
    # Ver que las matrices sean iguales
    if len(matriz1) != len(matriz2) or len(matriz1[0]) != len(matriz2[0]):
        return None

    # Crear una matriz resultado
    filas = len(matriz1)
    columnas = len(matriz1[0])
    resultado = [[0] * columnas for _ in range(filas)]

    # Sumar las matrices
    for i in range(filas):
        for j in range(columnas):
            resultado[i][j] = matriz1[i][j] + matriz2[i][j]

    return resultado

# Ejemplo
matriz1 = [[8, 12, 5], [7, 4, 9], [0, 6, 1]]
matriz2 = [[1, 7, 9], [1, 2, 2], [6, 6, 8]]
resultado = suma_matrices(matriz1, matriz2)

if resultado is None:
    print("Las matrices no tienen la misma dimensión.")
else:
    print("El resultado de la suma es:")
    for fila in resultado:
        print(fila)

El resultado de la suma es:
[9, 19, 14]
[8, 6, 11]
[6, 12, 9]


In [5]:
import numpy as np
# Codigo para invertir matrices 3x3
# Definir la matriz original
A = np.array([[1, 4, 3],
              [4, 8, 6],
              [7, 4, 9]])

# Calcular la matriz inversa
A_inv = np.linalg.inv(A)

print("Matriz original:")
print(A)
print("\nMatriz inversa:")
print(A_inv)


Matriz original:
[[1 4 3]
 [4 8 6]
 [7 4 9]]

Matriz inversa:
[[-1.00000000e+00  5.00000000e-01 -1.58603289e-17]
 [-1.25000000e-01  2.50000000e-01 -1.25000000e-01]
 [ 8.33333333e-01 -5.00000000e-01  1.66666667e-01]]


In [6]:
import numpy as np
#Codigo para invertir matrices con gauss jordan
def gauss_jordan(matrix):
    n = len(matrix)
    augmented_matrix = np.concatenate((matrix, np.identity(n)), axis=1)

    for i in range(n):
        pivot = augmented_matrix[i, i]
        augmented_matrix[i] /= pivot

        for j in range(n):
            if i != j:
                factor = augmented_matrix[j, i]
                augmented_matrix[j] -= factor * augmented_matrix[i]

    inverse_matrix = augmented_matrix[:, n:]
    return inverse_matrix

# Ejemplo de uso
matrix = np.array([[1, 2, 3], [0, 1, 4], [5, 6, 0]])
inverse = gauss_jordan(matrix)

print("Matriz original:")
print(matrix)

print("\nMatriz inversa:")
print(inverse)

Matriz original:
[[1 2 3]
 [0 1 4]
 [5 6 0]]

Matriz inversa:
[[-24.  18.   5.]
 [ 20. -15.  -4.]
 [ -5.   4.   1.]]


In [7]:
import numpy as np
#Codigo para saber el rango de una matriz
def matriz_rango(matrix):
    # Obtiene el rango de la matriz utilizando la factorización de valores singulares
    _, s, _ = np.linalg.svd(matrix)
    rango = np.sum(s > 1e-10)  # Considera valores singulares mayores a una tolerancia pequeña

    return rango

# Ejemplo de uso
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
rango = matriz_rango(matrix)

print("Matriz:")
print(matrix)

print("\nRango de la matriz:", rango)

Matriz:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Rango de la matriz: 2


In [8]:
import numpy as np
# Codigo para resolver sistemas de ecuaciones
# Definir las matrices A y b del sistema de ecuaciones Ax = b
A = np.array([[2, 3, -1],
              [4, 1, 2],
              [-1, 2, 3]])

b = np.array([7, 3, 8])

# Resolver el sistema de ecuaciones
x = np.linalg.solve(A, b)

print("Solución del sistema de ecuaciones:")
print(x)

Solución del sistema de ecuaciones:
[-0.30188679  2.77358491  0.71698113]


In [9]:
import numpy as np
from scipy.linalg import lu_factor, lu_solve
# Codigo para factorizar una matriz LU
# Definir la matriz A
A = np.array([[2, 3, 1],
              [4, 1, 2],
              [1, 2, 3]])

# Factorizar la matriz A en LU
lu, piv = lu_factor(A)

# Resolver un sistema de ecuaciones con la matriz factorizada
b = np.array([7, 3, 8])
x = lu_solve((lu, piv), b)

print("Matriz A:")
print(A)

print("\nMatriz LU:")
print(lu)

print("\nSolución del sistema de ecuaciones:")
print(x)


Matriz A:
[[2 3 1]
 [4 1 2]
 [1 2 3]]

Matriz LU:
[[4.   1.   2.  ]
 [0.5  2.5  0.  ]
 [0.25 0.7  2.5 ]]

Solución del sistema de ecuaciones:
[-0.48  2.2   1.36]


In [10]:
def calcular_determinante_sarrus(matriz):
    if len(matriz) != 3 or len(matriz[0]) != 3:
        raise ValueError("La matriz debe ser de 3x3")
 #Aqui se calcula la determinante
    determinante = (
        matriz[0][0] * matriz[1][1] * matriz[2][2] +
        matriz[0][1] * matriz[1][2] * matriz[2][0] +
        matriz[0][2] * matriz[1][0] * matriz[2][1] -
        matriz[0][2] * matriz[1][1] * matriz[2][0] -
        matriz[0][0] * matriz[1][2] * matriz[2][1] -
        matriz[0][1] * matriz[1][0] * matriz[2][2]
    )
 #Solo se pueden usar matrices 3x3
    return determinante

# Ejemplo de uso
matriz_ejemplo = [[4, 2, 7], [4, 1, 6], [7, 3, 1]]
determinante = calcular_determinante_sarrus(matriz_ejemplo)
print("La determinante de la matriz es:", determinante)

La determinante de la matriz es: 43


In [11]:
import numpy as np
#Codigo con numpy para resolver matrices con gauss jordan
def gauss_jordan(matriz):
    filas, columnas = matriz.shape
    for i in range(filas):
        # Paso 1: Buscar el pivote en la columna actual
        pivote = matriz[i][i]
        if pivote == 0:
            raise ValueError("La matriz no se puede resolver mediante Gauss-Jordan")

        # Paso 2: Dividir la fila por el pivote para hacerlo igual a 1
        matriz[i] = matriz[i] / pivote

        # Paso 3: Restar múltiplos de la fila actual para hacer ceros en el resto de la columna
        for j in range(filas):
            if j != i:
                multiplicador = matriz[j][i]
                matriz[j] = matriz[j] - multiplicador * matriz[i]

    return matriz

# Ejemplo de uso
matriz_ejemplo = np.array([[1, 2, -1, 4], [2, 3, 1, 5], [1, -1, 2, 1]])
matriz_resuelta = gauss_jordan(matriz_ejemplo)
print("La matriz resuelta mediante Gauss-Jordan es:")
print(matriz_resuelta)

La matriz resuelta mediante Gauss-Jordan es:
[[ 1  0  0  3]
 [ 0  1  0  0]
 [ 0  0  1 -1]]


In [12]:
import numpy as np
#Codigo para resolver matrices con crammer
def resolver_cramer(coeficientes, constantes):
    matriz_coeficientes = np.array(coeficientes)
    matriz_constantes = np.array(constantes)
    num_ecuaciones, num_variables = matriz_coeficientes.shape

    if num_ecuaciones != num_variables:
        raise ValueError("El número de ecuaciones debe ser igual al número de variables")

    determinante_principal = np.linalg.det(matriz_coeficientes)

    if determinante_principal == 0:
        raise ValueError("El sistema de ecuaciones no tiene solución única")

    soluciones = []

    for i in range(num_variables):
        matriz_sustituida = matriz_coeficientes.copy()
        matriz_sustituida[:, i] = matriz_constantes
        determinante_sustituido = np.linalg.det(matriz_sustituida)
        solucion = determinante_sustituido / determinante_principal
        soluciones.append(solucion)

    return soluciones

# Ejemplo de uso
coeficientes = [[2, 3, -1], [1, -2, 1], [3, 1, -2]]
constantes = [7, 3, 10]

soluciones = resolver_cramer(coeficientes, constantes)
print("Las soluciones del sistema son:", soluciones)

Las soluciones del sistema son: [3.2857142857142847, 0.14285714285714302, 4.44089209850063e-16]


In [13]:
import numpy as np
#codigo para calcular subespacios generadores
def calcular_subespacios_generadores(vectores):
    matriz = np.array(vectores)
    rref_matriz = np.linalg.matrix_rank(matriz)
    dimension_espacio = matriz.shape[1]

    if rref_matriz < dimension_espacio:
        return "El conjunto de vectores no genera un subespacio de dimensión máxima."

    subespacios_generadores = []
    for i in range(1, dimension_espacio + 1):
        combinaciones = np.array([list(comb) for comb in itertools.combinations(vectores, i)])
        for combinacion in combinaciones:
            if np.linalg.matrix_rank(combinacion) == dimension_espacio:
                subespacios_generadores.append(combinacion)

    return subespacios_generadores

In [14]:
import numpy as np

def es_dependiente(vectores):
    matriz = np.array(vectores)
    rref_matriz = np.linalg.matrix_rank(matriz)
    num_vectores = matriz.shape[0]

    if rref_matriz < num_vectores:
        return True
    else:
        return False

# Ejemplo de uso
vectores_dependientes = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
vectores_independientes = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]

print("Vectores dependientes:", es_dependiente(vectores_dependientes))
print("Vectores independientes:", es_dependiente(vectores_independientes))

Vectores dependientes: True
Vectores independientes: False


In [15]:
import numpy as np

def calcular_base_y_dimension(matriz):
    rref_matriz = np.linalg.matrix_rank(matriz)
    dimension = matriz.shape[1]

    # Obtener base a partir de las columnas no nulas de la matriz en su forma escalonada reducida
    base = matriz[:, :rref_matriz].T

    return base, dimension

def calcular_coordenadas(vector, base):
    coordenadas = np.linalg.solve(base, vector)
    return coordenadas

def calcular_matriz_cambio_de_base(base_origen, base_destino):
    matriz_cambio = np.linalg.inv(base_origen) @ base_destino
    return matriz_cambio

# Ejemplo de uso
base_origen = np.array([[1, 4, 3], [4, 7, 5], [1, 7, 9]])
base_destino = np.array([[1, 0, 0], [0, 1, 0], [0, 0, 1]])
vector = np.array([2, 4, 6])

base, dimension = calcular_base_y_dimension(base_origen)
coordenadas = calcular_coordenadas(vector, base)
matriz_cambio = calcular_matriz_cambio_de_base(base_origen, base_destino)

print("Base y dimensión:", base, dimension)
print("Coordenadas del vector en la base:", coordenadas)
print("Matriz de cambio de base:", matriz_cambio)

Base y dimensión: [[1 4 1]
 [4 7 7]
 [3 5 9]] 3
Coordenadas del vector en la base: [-1.75757576  0.72727273  0.84848485]
Matriz de cambio de base: [[-0.84848485  0.45454545  0.03030303]
 [ 0.93939394 -0.18181818 -0.21212121]
 [-0.63636364  0.09090909  0.27272727]]


In [16]:
import numpy as np

def calcular_espacio_ortonormal(vectores):
    matriz = np.array(vectores)
    q, _ = np.linalg.qr(matriz)
    return q

def calcular_espacio_ortogonal(vectores):
    matriz = np.array(vectores)
    q, r = np.linalg.qr(matriz)
    return np.linalg.solve(r, np.eye(r.shape[0]))

# Ejemplo de uso
vectores = [[1, 0, 0], [0, 1, 0], [1, 1, 1]]

vectores_ortonormales = calcular_espacio_ortonormal(vectores)
vectores_ortogonales = calcular_espacio_ortogonal(vectores)

print("Vectores ortonormales:")
for vector in vectores_ortonormales:
    print(vector)

print("\nVectores ortogonales:")
for vector in vectores_ortogonales:
    print(vector)

Vectores ortonormales:
[-0.70710678  0.40824829 -0.57735027]
[-0.         -0.81649658 -0.57735027]
[-0.70710678 -0.40824829  0.57735027]

Vectores ortogonales:
[-0.70710678  0.40824829 -0.57735027]
[-0.         -0.81649658 -0.57735027]
[0.         0.         1.73205081]


In [17]:
import numpy as np

# Definir la matriz de la transformación lineal
A = np.array([[3, 5, 7],
              [8, 5, 5],
              [4, 8, 8]])

# Calcular el núcleo (espacio nulo) de la transformación
null_space = np.linalg.svd(A)[2][np.abs(np.linalg.svd(A)[1]) < 1e-15].T
print("Núcleo de la transformación lineal:")
print(null_space)

# Calcular la imagen de la transformación
image = np.linalg.matrix_rank(A)
print("Imagen de la transformación lineal:")
print(image)

Núcleo de la transformación lineal:
[]
Imagen de la transformación lineal:
3


In [18]:
import numpy as np

# Definir una matriz
matriz = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Calcular los valores y vectores propios
valores_propios, vectores_propios = np.linalg.eig(matriz)

# Imprimir los valores propios
print("Valores propios:")
print(valores_propios)

# Imprimir los vectores propios
print("Vectores propios:")
print(vectores_propios)

Valores propios:
[ 1.61168440e+01 -1.11684397e+00 -1.30367773e-15]
Vectores propios:
[[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]


In [19]:
import numpy as np

# Definir una matriz
matriz = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Calcular los valores y vectores propios
valores_propios, vectores_propios = np.linalg.eig(matriz)

# Construir la matriz diagonal con los valores propios
matriz_diagonal = np.diag(valores_propios)

# Calcular la matriz de cambio de base inversa
matriz_cambio_base_inv = np.linalg.inv(vectores_propios)

# Calcular la potencia de la matriz utilizando el teorema de Cayley-Hamilton
potencia_matriz = matriz_cambio_base_inv @ matriz_diagonal @ vectores_propios

# Imprimir la potencia de la matriz
print("Potencia de la matriz:")
print(potencia_matriz)

Potencia de la matriz:
[[ 1.45742711  6.05914621 -3.71879861]
 [ 3.28554614 11.60099488 -6.26646263]
 [-2.00533234 -5.24961527  1.94157802]]


In [20]:
import numpy as np

# Definir una matriz
matriz = np.array([[1, 2], [3, 4]])

# Calcular los valores y vectores propios
valores_propios, vectores_propios = np.linalg.eig(matriz)

# Crear una matriz diagonal con los valores propios
matriz_diagonal = np.diag(valores_propios)

# Calcular la matriz de cambio de base
matriz_cambio_base = np.linalg.inv(vectores_propios)

# Calcular la matriz diagonalizada
matriz_diagonalizada = matriz_cambio_base @ matriz @ np.linalg.inv(matriz_cambio_base)

# Imprimir la matriz diagonalizada
print("Matriz diagonalizada:")
print(matriz_diagonalizada)

Matriz diagonalizada:
[[-3.72281323e-01  8.58652695e-16]
 [-9.05095691e-17  5.37228132e+00]]
